// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolXAPI.Data;

namespace SchoolXAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("SchoolXAPI.Models.Image.Image", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateCreate = new DateTime(2022, 4, 25, 10, 24, 5, 980, DateTimeKind.Local).AddTicks(7939),
                            Name = "y43b6ZbH3P",
                            Path = "c:\\temp\\image1.png",
                            Size = "640x480"
                        },
                        new
                        {
                            Id = 2L,
                            DateCreate = new DateTime(2021, 9, 10, 2, 54, 21, 776, DateTimeKind.Local).AddTicks(5654),
                            Name = "f9HV0vcZ6l",
                            Path = "c:\\temp\\image2.png",
                            Size = "640x480"
                        },
                        new
                        {
                            Id = 3L,
                            DateCreate = new DateTime(2021, 12, 19, 18, 30, 53, 281, DateTimeKind.Local).AddTicks(3597),
                            Name = "0BmKlyDrBt",
                            Path = "c:\\temp\\image3.png",
                            Size = "640x480"
                        },
                        new
                        {
                            Id = 4L,
                            DateCreate = new DateTime(2021, 12, 28, 5, 22, 9, 274, DateTimeKind.Local).AddTicks(2580),
                            Name = "CULDdrX4Gm",
                            Path = "c:\\temp\\image4.png",
                            Size = "640x480"
                        },
                        new
                        {
                            Id = 5L,
                            DateCreate = new DateTime(2022, 5, 11, 12, 11, 15, 351, DateTimeKind.Local).AddTicks(7367),
                            Name = "OcMe6wa7x4",
                            Path = "c:\\temp\\image5.png",
                            Size = "640x480"
                        },
                        new
                        {
                            Id = 6L,
                            DateCreate = new DateTime(2021, 6, 19, 12, 17, 40, 726, DateTimeKind.Local).AddTicks(9189),
                            Name = "ELqSvXVWY4",
                            Path = "c:\\temp\\image6.png",
                            Size = "640x480"
                        },
                        new
                        {
                            Id = 7L,
                            DateCreate = new DateTime(2021, 11, 21, 1, 48, 10, 774, DateTimeKind.Local).AddTicks(6884),
                            Name = "x2bZlhZ85R",
                            Path = "c:\\temp\\image7.png",
                            Size = "640x480"
                        },
                        new
                        {
                            Id = 8L,
                            DateCreate = new DateTime(2021, 9, 4, 13, 41, 27, 640, DateTimeKind.Local).AddTicks(1868),
                            Name = "oCLeU4a7GY",
                            Path = "c:\\temp\\image8.png",
                            Size = "640x480"
                        },
                        new
                        {
                            Id = 9L,
                            DateCreate = new DateTime(2022, 4, 18, 21, 37, 13, 810, DateTimeKind.Local).AddTicks(6030),
                            Name = "XHGKuhs3Qx",
                            Path = "c:\\temp\\image9.png",
                            Size = "640x480"
                        },
                        new
                        {
                            Id = 10L,
                            DateCreate = new DateTime(2021, 9, 18, 12, 8, 49, 214, DateTimeKind.Local).AddTicks(2741),
                            Name = "tLka2AW0Id",
                            Path = "c:\\temp\\image10.png",
                            Size = "640x480"
                        });
                });

            modelBuilder.Entity("SchoolXAPI.Models.User.UserItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateCreate = new DateTime(2021, 7, 30, 19, 56, 24, 561, DateTimeKind.Local).AddTicks(439),
                            Email = "Lilyan51@hotmail.com",
                            Name = "Domenic Baumbach",
                            Password = "AqnOd7m6IB",
                            Phone = "431998"
                        },
                        new
                        {
                            Id = 2L,
                            DateCreate = new DateTime(2022, 3, 19, 4, 6, 16, 161, DateTimeKind.Local).AddTicks(94),
                            Email = "Retta.Emard@gmail.com",
                            Name = "Crystal Jast",
                            Password = "w4tDHafiS9",
                            Phone = "986811"
                        },
                        new
                        {
                            Id = 3L,
                            DateCreate = new DateTime(2022, 3, 11, 17, 55, 42, 38, DateTimeKind.Local).AddTicks(749),
                            Email = "Camila_Treutel19@gmail.com",
                            Name = "Sydnie Runte",
                            Password = "9frx9bzHGp",
                            Phone = "113979"
                        },
                        new
                        {
                            Id = 4L,
                            DateCreate = new DateTime(2022, 2, 5, 0, 24, 31, 843, DateTimeKind.Local).AddTicks(8772),
                            Email = "Darion84@yahoo.com",
                            Name = "Blair Stamm",
                            Password = "Cgwfiul7kO",
                            Phone = "827865"
                        },
                        new
                        {
                            Id = 5L,
                            DateCreate = new DateTime(2021, 8, 23, 21, 42, 40, 215, DateTimeKind.Local).AddTicks(2335),
                            Email = "Bobbie73@yahoo.com",
                            Name = "Garrison Lindgren",
                            Password = "IeoY3vqJnK",
                            Phone = "482847"
                        },
                        new
                        {
                            Id = 6L,
                            DateCreate = new DateTime(2021, 9, 7, 13, 25, 38, 285, DateTimeKind.Local).AddTicks(1085),
                            Email = "Bethel.Vandervort@yahoo.com",
                            Name = "Elwin Jacobi",
                            Password = "oCawS5eeCn",
                            Phone = "292301"
                        },
                        new
                        {
                            Id = 7L,
                            DateCreate = new DateTime(2021, 8, 6, 19, 59, 0, 312, DateTimeKind.Local).AddTicks(5690),
                            Email = "Trent_Harber@hotmail.com",
                            Name = "Golda Prohaska",
                            Password = "JfLe8jC5iC",
                            Phone = "680739"
                        },
                        new
                        {
                            Id = 8L,
                            DateCreate = new DateTime(2021, 12, 18, 2, 39, 34, 717, DateTimeKind.Local).AddTicks(3116),
                            Email = "Daphney84@yahoo.com",
                            Name = "Viola Hane",
                            Password = "qumoo3261a",
                            Phone = "875804"
                        },
                        new
                        {
                            Id = 9L,
                            DateCreate = new DateTime(2022, 4, 17, 13, 3, 40, 938, DateTimeKind.Local).AddTicks(576),
                            Email = "Ella90@yahoo.com",
                            Name = "Cecile Volkman",
                            Password = "wik2TZ7jra",
                            Phone = "331261"
                        },
                        new
                        {
                            Id = 10L,
                            DateCreate = new DateTime(2022, 3, 21, 10, 2, 14, 283, DateTimeKind.Local).AddTicks(6539),
                            Email = "Rahul39@hotmail.com",
                            Name = "Anahi Powlowski",
                            Password = "F_m2tr5Ack",
                            Phone = "906033"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
